name: data-manipulation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - alabaster=0.7.12
  - alsa-lib=1.2.3
  - anyio=3.4.0
  - argon2-cffi=21.1.0
  - arrow=1.2.1
  - arrow-cpp=5.0.0
  - asgiref=3.4.1
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.3.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.9
  - click=8.0.3
  - cmarkgfm=0.7.0
  - colorama=0.4.4
  - commonmark=0.9.1
  - cookiecutter=1.7.3
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - django=4.0.4
  - dnspython=2.1.0
  - docutils=0.17.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.28.4
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.70.2
  - glib-tools=2.70.2
  - glog=0.5.0
  - grpc-cpp=1.40.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=68.2
  - idna=3.1
  - imagesize=1.3.0
  - importlib-metadata=4.9.0
  - importlib_metadata=4.9.0
  - importlib_resources=5.4.0
  - ipykernel=6.6.0
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jbig=2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.3.1
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.9.0
  - keyring=23.4.0
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - lxml=4.8.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.27
  - mysql-connector-python=8.0.27
  - mysql-libs=8.0.27
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - notebook=6.4.11
  - nspr=4.32
  - nss=3.73
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - orc=1.7.0
  - packaging=21.3
  - pandas=1.4.2
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pkginfo=1.8.2
  - platformdirs=2.3.0
  - poyo=0.5.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - protobuf=3.18.1
  - psycopg2=2.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py4j=0.10.9.2
  - pyarrow=5.0.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pyspark=3.2.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-slugify=5.0.2
  - python_abi=3.9
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.12.9
  - re2=2021.09.01
  - readline=8.1
  - readme_renderer=27.0
  - requests=2.26.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.5.0
  - rich=12.4.1
  - s2n=1.0.10
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - setuptools=59.6.0
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.1
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.37.0
  - sqlparse=0.4.2
  - statsmodels=0.13.1
  - terminado=0.12.1
  - testpath=0.5.0
  - text-unidecode=1.3
  - tk=8.6.11
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - twine=4.0.0
  - typed-ast=1.5.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - unidecode=1.3.2
  - urllib3=1.26.7
  - versioneer=0.22
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.0
  - xlsxwriter=3.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
