site_name: data_manipulation
site_author: Shawn Ng

theme:
  name: material

hooks:
  - docs/hooks.py

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - base: api/base.md
    - beautifulsoup_: api/beautifulsoup_.md
    - boto3_: api/boto3_.md
    - cryptography_: api/cryptography_.md
    - django_: api/django_.md
    - kerberos_: api/kerberos_.md
    - mysql_connector_python_: api/mysql_connector_python_.md
    - pandas_: api/pandas_.md
    - polars_: api/polars_.md
    - postgres_: api/postgres_.md
    - pyspark_: api/pyspark_.md
    - smtplib_: api/smtplib_.md
    - sqlalchemy_: api/sqlalchemy_.md
  - Changelog: changelog.md
