name: data-manipulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - beautifulsoup4
  - cookiecutter
  - notebook
  - jupyterlab
  - matplotlib
  - pandas
  - psycopg2
  - pyspark
  - seaborn
  - sphinx
  - tqdm
  - twine
  - django
  - versioneer
